repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0
  hooks:
  - id: flake8
    args:
    - --ignore=W391,F401
    - --exclude=docs/*,tests/*
    - --max-line-length=131
  - id: check-ast
  - id: debug-statements
  - id: fix-encoding-pragma
  - id: end-of-file-fixer
  - id: check-merge-conflict
- repo: https://github.com/ambv/black.git
  rev: 18.6b2
  hooks:
  - id: black
    python_version: python3.6
